//
//  api.c
//	This file is part of a HK17 Algorithm Implementation
//  Implemented by Matias Teragni - 2017. 
//
//  This files declares the interface dictated by NIST on the file api.h for the HK17 algorithm

//functions
// crypto_kem_keypair
//    this function creates all the public random data required by the algorithm, the private data for both nodes
//	  and the public token associated with one of the nodes, fitting all of it into the structures required by NIST
// crypto_kem_enc
//    this function takes part of the data generated by crypto_kem_keypair and builds the other public token , 
//	  along with the shared secret to be used in the validation
// crypto_kem_dec
//    this function takes the second public token and calculates the shared secret from the view of the second node
//	  then it returns that data to be validated against the result of crypto_kem_enc


#define CRYPTO_SECRETKEYBYTES 336 
#define CRYPTO_PUBLICKEYBYTES 464 
#define CRYPTO_BYTES 64 
#define CRYPTO_CIPHERTEXTBYTES 64 
 
 

#define CRYPTO_ALGNAME "HK17_8bit"
#include "HK17.h"
int crypto_kem_keypair(unsigned char *pk, unsigned char *sk);

int crypto_kem_enc(unsigned char *ct, unsigned char *ss, const unsigned char *pk);
int crypto_kem_dec(unsigned char *ss, const unsigned char *ct, const unsigned char *sk);
