kat_kem.rsp: kat
	./run

kat: Makefile nist/kat_kem.c nist/rng.c nist/rng.h randombytes.h benes.c bm.c controlbits.c decrypt.c encrypt.c fft.c fft_tr.c gf.c operations.c pk_gen.c sk_gen.c transpose.c util.c vec128.c vec256.c  consts.S syndrome_asm.s transpose_64x128_sp_asm.s update_asm.s vec128_mul_asm.s vec256_ama_asm.s vec256_maa_asm.s vec256_mul_asm.s vec_reduce_asm.s   
	./build
